core/urls.py
from django.contrib import admin
from django.urls import path ,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('store.urls',namespace='store'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

store/urls.py
from django.urls import path
from . import views
from .login_required.auth import auth_middleware

app_name = 'store'

urlpatterns = [
    path('',views.homefunc,name='home'),
    path('signup/',views.signupfunc,name='signup'),
    path('menu/',views.menufunc,name='menu'),
    path('login/',views.loginfunc,name='login'),
    path('logout/',views.logoutfunc,name='logout'),
    path('about/',views.aboutfunc,name='about'),
    path('gallery/',views.galleryfunc,name='gallery'),
    path('contactus/',views.contactusfunc,name='contactus'),
    path('cart/', views.cart, name='cart'),
    path('checkout/', views.Checkout, name='checkout'),
    path('orders/', views.orders, name='orders'),
    path('search/',views.search,name='itemsearch'),
    path('visualize/',views.visualize,name='visualize'),
    path('optimize/',views.optimize,name='optimize'),
    path('pay/', views.payment, name='pay'),
    path('rsearch/',views.search_product,name='search'),
    path('rpay/', views.Roompayment, name='roompay'),
    path('rcheck/', views.roomcheckout, name='roomcheck'),
    path('rorders/', views.roomorders, name='roomorders'),
    path('rooms/', views.room, name='rooms'),
    path('roomcart/',views.roomcart,name='roomcart'),
    
    path('menu/<slug:menu_slug>/',views.categorymenufunc,name='categorymenu'),
    path('<slug:item_slug>/',views.eachitemfunc,name='eachitem')
]

store/forms.py
from django import forms
from django.contrib.auth.password_validation import validate_password


class SignupForm(forms.Form):
    username = forms.CharField(max_length=100,)
    email = forms.EmailField()
    password1 = forms.CharField(widget=forms.PasswordInput,validators=[validate_password])
    password2 = forms.CharField(widget=forms.PasswordInput,validators=[validate_password])

store/views.py
from django.shortcuts import render,get_object_or_404,redirect
from django.contrib.auth.models import User,auth
from django.contrib import messages
from .models import Menu,Items,Nonveg,Veg,Beverages,Desserts,Gallery1,Gallery2,Contactus,allItems,Order,Check,Pay,RoomOrder,RoomCheck,Room
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from .forms import *
from .contactus import *
from .utils import *
from rsome import ro
from rsome import grb_solver as grb
from django.core.mail import send_mail
from django.conf import settings

# Create your views here.

def menudeffunc(request):
    return {
        'menu' : Menu.objects.all()
    }


def homefunc(request):
    print(request.user.id)
    request.session['roomcart'] = {}
    request.session['cart'] = {}
    return render(request, 'home.html')

def loginfunc(request):
    return_url = None
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = auth.authenticate(username=username,password=password)
        if user is not None:
            auth.login(request, user)
            if 'next' in request.POST:
                return redirect(request.POST.get('next'))
            else:
                return redirect("/")
        else:
            msg = "**incorrect credentials**"
            return render(request, 'signup.html',{'msg':msg})
    else:
        loginfunc.return_url=request.GET.get('return_url')  
        return render(request, 'login.html')

def logoutfunc(request):
    auth.logout(request)
    return redirect("/")

def aboutfunc(request):
    return render(request, 'aboutus.html')

def signupfunc(request):
    if request.method == 'POST':
        email = request.POST['email']
        username = request.POST['username']
        password1 = request.POST['password1']
        password2 = request.POST['password2']
        if password1 == password2 :
            if User.objects.filter(username=username).exists():
                msg = "----username exixts-----"
                return render(request, 'signup.html',{'msg':msg})
            elif User.objects.filter(email=email).exists():
                msg = "------email taken------"
                return render(request, 'signup.html',{'msg':msg})
            else:
                form = SignupForm(request.POST)
                if form.is_valid():
                    user = User.objects.create_user(username=username,password=password1,email=email)
                    user.save()
                    subject = 'Successful Registration'
                    message = "Welcome To Cosmopolitan '"+username+"' . ThankYou for Signing up to our website! Explore it make use of it's services"
                    recipient = email
                    send_mail(subject,
                          message, settings.EMAIL_HOST_USER, [recipient], fail_silently=False)
                    print("--------user created---------")
                    return render(request, 'login.html')
                else:
                    print("---django form validation didn't work---")
                    return render(request, 'signup.html')
        else:
            msg = "**failed to save user**"
            print("failed to save user")
            return render(request, 'signup.html',{'msg':msg})
    else:
        return render(request, 'signup.html')

def menufunc(request):
    items = Items.objects.all()
    menu = Menu.objects.all()
    return render(request, 'menu.html',{'items':items,'menu':menu})

def galleryfunc(request):
    gal1 = Gallery1.objects.all()
    gal2 = Gallery2.objects.all()
    return render(request, 'gallery.html',{'gal1':gal1,'gal2':gal2})

@login_required(redirect_field_name='next')
def contactusfunc(request):
    if request.method=='POST':
        name = request.POST['name']
        email = request.POST['email']
        message = request.POST['message']
        form = ContactusForm(request.POST)
        if form.is_valid():
            sent = Contactus(name=name,email=email,message=message)
            sent.save()
            subject = 'Resolve Issue'
            message = "ThankYou for contacting us '"+name+"' . We will make sure to resolve your issue as soon as possible and get back to you soon."
            recipient = email
            send_mail(subject,
                          message, settings.EMAIL_HOST_USER, [recipient], fail_silently=False)
            msg = "message sent"
            print("message saved-------------------------")
            return render(request, 'contact.html',{'msg':msg})
        else:
            msg = "inalid credentials"
            print("enter valid credentials-----------")
            return render(request, 'contact.html',{'msg':msg})
    else:
        return render(request, 'contact.html')



@login_required(redirect_field_name='next')
def eachitemfunc(request,item_slug):
    item_n = Nonveg.objects.filter(slug = item_slug)
    item_v = Veg.objects.filter(slug = item_slug)
    item_b = Beverages.objects.filter(slug = item_slug)
    item_d = Desserts.objects.filter(slug = item_slug)
    if item_n:
        if request.method == 'POST':
            item = get_object_or_404(Nonveg, slug=item_slug)
            items = request.POST.get('items')
            remove = request.POST.get('remove')
            cart = request.session.get('cart')
            if cart:
                quantity = cart.get(items)
                if quantity:
                    if remove:
                        if quantity <= 1:
                            cart.pop(items)
                        else:
                            cart[items] = quantity - 1
                    else:
                        cart[items] = quantity + 1

                else:
                    cart[items] = 1
            else:
                cart = {}
                cart[items] = 1
            request.session['cart'] = cart

            return render(request, 'item.html', {'item': item})

        else:
            item = get_object_or_404(Nonveg, slug=item_slug)
            rating = allItems.objects.values_list('rating',flat=True).get(name=item)
            return render(request, 'item.html', {'item': item,'rating':rating})
    if item_v:
        if request.method == 'POST':
            item = get_object_or_404(Veg, slug=item_slug)
            items = request.POST.get('items')
            remove = request.POST.get('remove')

            cart = request.session.get('cart')
            if cart:
                quantity = cart.get(items)
                if quantity:
                    if remove:
                        if quantity <= 1:
                            cart.pop(items)
                        else:
                            cart[items] = quantity - 1
                    else:
                        cart[items] = quantity + 1

                else:
                    cart[items] = 1
            else:
                cart = {}
                cart[items] = 1
            request.session['cart'] = cart

            return render(request, 'item.html', {'item': item})
        else:
            item = get_object_or_404(Veg, slug=item_slug)
            rating = allItems.objects.values_list('rating',flat=True).get(name=item)
            return render(request, 'item.html', {'item': item,'rating':rating})
    if item_b:
        if request.method == 'POST':
            item = get_object_or_404(Beverages, slug=item_slug)
            items = request.POST.get('items')
            remove = request.POST.get('remove')

            cart = request.session.get('cart')
            if cart:
                quantity = cart.get(items)
                if quantity:
                    if remove:
                        if quantity <= 1:
                            cart.pop(items)
                        else:
                            cart[items] = quantity - 1
                    else:
                        cart[items] = quantity + 1

                else:
                    cart[items] = 1
            else:
                cart = {}
                cart[items] = 1
            request.session['cart'] = cart

            return render(request, 'item.html', {'item': item})
        else:
            item = get_object_or_404(Beverages, slug=item_slug)
            rating = allItems.objects.values_list('rating',flat=True).get(name=item)
            return render(request, 'item.html', {'item': item,'rating':rating})
    if item_d:
        if request.method == 'POST':
            item = get_object_or_404(Desserts, slug=item_slug)
            items = request.POST.get('items')
            remove = request.POST.get('remove')

            cart = request.session.get('cart')
            if cart:
                quantity = cart.get(items)
                if quantity:
                    if remove:
                        if quantity <= 1:
                            cart.pop(items)
                        else:
                            cart[items] = quantity - 1
                    else:
                        cart[items] = quantity + 1

                else:
                    cart[items] = 1
            else:
                cart = {}
                cart[items] = 1
            request.session['cart'] = cart

            return render(request, 'item.html', {'item': item})
        else:
            item = get_object_or_404(Desserts, slug=item_slug)
            rating = allItems.objects.values_list('rating',flat=True).get(name=item)
            return render(request, 'item.html', {'item': item,'rating':rating})


@login_required(redirect_field_name='next')
def categorymenufunc(request,menu_slug):
    category = get_object_or_404(Menu,slug=menu_slug)
    items = Items.objects.filter(menu=category)
    if menu_slug == "non-veg":
        nv = Nonveg.objects.all()
        return render(request, 'category.html',{'category':category,'nv':nv}) 
    elif menu_slug == "veg" :
        nv = Veg.objects.all()

store/templates/bookings.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="{% static 'bookings.css' %}">
    <!-- <script src="booking.js"></script> -->
    <title>SDP project</title>
  </head>


  <body>
    <!--navbar start-->
    <div class="fixed-top">
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
          
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
            <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            <img src="{{ '/media/images/user.svg' }}">
          </a>
          
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
          {% if user.is_authenticated %}
            <li><a class="nav-link dropdown-item" href="">{{ user.username|title }}</a></li>
            <hr>
            <li class="selected">
            <a class="nav-link dropdown-item" href="{% url 'store:orders' %}" >Order History</a>
            </li>
            <li class="selected">
            <a class="nav-link dropdown-item" href="{% url 'store:roomorders' %}" >Booking History</a>
            </li>
            <li class="selected">
            <a class="nav-link dropdown-item" href="{% url 'store:logout' %}" >Logout</a>
            </li>
            {% else %}
            <li class="selected">
            <a class="nav-link dropdown-item" href="{% url 'store:signup' %}" >Signup</a>
            </li>
            <hr>
            <li class="selected">
            <a class="nav-link dropdown-item" href="{% url 'store:login' %}" >Login</a>
            </li>
            {% endif %}
            </ul>
            
        </li>
         
              <li class="nav-item">
                <a class="nav-link" href="{% url 'store:home' %}">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" aria-current="page" href="{% url 'store:menu' %}">Menu</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'store:rooms' %}">Book Rooms</a>
              </li>
              {% if user.is_authenticated %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'store:cart' %}">Cart</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'store:roomcart' %}">Bookings-Cart</a>
              </li>
              {% endif %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'store:about' %}">About</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'store:home' %}#ourteam">Our team</a>
              </li>

              {% if user.username == 'admin' %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'store:visualize' %}">Visualize</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'store:optimize' %}">Optimize</a>
              </li>
              {% endif %}
            </ul>
          </div>
        </div>
    </nav>
    

    </div>
    <!--navbar ends-->


    <br>
    <br>
    <br>
    <br>
<h2 style="text-align: center;"><strong><u>ROOMS</u></strong></h2>
    <hr>
    <br><br>
    <hr>
     <form name="myform" method="GET" action="{% url 'store:search' %}">
    {% csrf_token %}

      From:&nbsp;<input type="date" name="checkin"  required>&nbsp;&nbsp;&nbsp;
      No. of days:&nbsp;<input type="number" min="1" name="daycount" required>&nbsp;&nbsp;&nbsp;
      Adult:&nbsp;<input type="number" name="q" placeholder="above 12 years" value="{{request.GET.q}}" required>&nbsp;&nbsp;&nbsp;
      Children:&nbsp;<input type="number" name="childrencount" placeholder="0-12 years" required>&nbsp;&nbsp;&nbsp;
<!--      <button onclick="searchfunction()">search</button>-->

    <input type="submit" name="submit" value="Search">
</form>
    <hr>

{% for result in results %}
                    <div class="card mx-auto mb-3" id={{result.id}} style="width: 18rem;">
                    <img class="card-img-top" src="{{result.image.url}}" alt="Card image cap">
                    <div class="card-body">
                        <p class="card-title">{{result.name}}</p>
                        <p class="card-text"><b>{{result.price}}/- Per Day</b></p>
                        <p class="card-text"><b>Adults:{{result.adult}}</b></p>
                        <p class="card-text"><b>Children:{{result.children}}</b></p>

    <form action="{% url 'store:rooms' %}"  method="POST">
                        {% csrf_token %}


                    <div class="card-footer p-0 no-gutters">



                            <input hidden type="hidden" name='product' value='{{result.id}}'>
                            <input type="submit" class="float-right btn btn-light  form-control"
                                   value="Add To Cart">
                                    </div>
    </form>
        </div>
    </div>

    {% endfor %}
<script>
  const searchfunction = () =>{
    let adult = document.getElementById('adultcount').value;
    let children = document.getElementById('childrencount').value;
    let rooms = document.getElementById('rooms');
    let des = rooms.getElementsByClassName('card-body');
    for(var i=0;i<des.length;i++)
    {
        let p = des[i].getElementsByTagName('p')[0];
        if(p)
        {
            let val = td.textContent || td.innerHTML;
            if(adult.indexOf(val) > -1)
            {
                des[i].style.display = "";
            }
            else{
                des[i].style.display="none";
            }
        }
    }
  }
</script>
    <br>
    <br>
    <br>

    <!-- book now start -->
    
    
    </div>
  
<!-- book now end -->

<br>
<br>
<br>


<!-- rooms start -->
<div class="container-fluid mt-3">


        <!-- filter -->


        <!-- all products -->
        <div id='products' class="col-lg-9 mx-auto">
            <div class="row mx-auto">
                {% for product in Rooms %}
                <div class="card mx-auto mb-3" id={{product.id}} style="width: 18rem;">
                    <img class="card-img-top" src="{{product.image.url}}" alt="Card image cap">
                    <div class="card-body">
                        <p class="card-title">{{product.name}}</p>
                        <p class="card-text"><b>{{product.price}}/- Per Day</b></p>
                        <p class="card-text"><b>Adults:{{product.adult}}</b></p>
                        <p class="card-text"><b>Children:{{product.children}}</b></p>

    <form action="{% url 'store:rooms' %}"  method="POST">
                        {% csrf_token %}


                    <div class="card-footer p-0 no-gutters">



                            <input hidden type="hidden" name='product' value='{{product.id}}'>
                            <input type="submit" class="float-right btn btn-light  form-control"
                                   value="Add To Cart">
                                    </div>
    </form>
        </div>
    </div>





{% endfor %}

</div>
  </div>
  </div>
</div>

<!-- rooms end -->

<br>
<br>
<br>


<!--page footer start-->
<div class="bg-dark footer">
  <div class="container">
     <div class="row text-center">
       <a href="home.html"><img src="{{ '/media/images/below-logo.jpeg' }}" ></a>
     </div>

     <hr style="color:gray">

     <div class="row text-center" style="color: ivory;">
       <div class="col">
         <ul>
           
            <h5><u>QUICK LINKS</u></h5>
           
           <li>
            <a href="contact.html">contact us</a>
          </li>
          <li>
            <a href="gallery.html">gallery</a>
          </li>
          <li>
            <a href="home.html#ourteam">our team</a>
          </li>
          <li>
            <a href="aboutus.html">about us</a>
          </li>
         </ul>
       </div>

       <div class="col">
        <h5><u>ADDRESS</u></h5> 
        <p>Cosmopolitan Restaurant,<br>Hyderabad.<br>pincode:500 020<br>email: abc@gmail.com</p>
       </div>

       <div class="col">
         <h5><u>VISIT US AT</u></h5>
         
         <a href="#facebook" class="fa fa-facebook"></a>
         <a href="https://youtu.be/mAFltQ2H8nA" class="fa fa-youtube"></a>
         <a href="#instagram" class="fa fa-instagram"></a>
       </div>
     </div>
  </div>
</div>
  <!--page footer ends-->

  </body>
  </html>

store/templates/category.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="{% static 'category.css' %}">
    <title>SDP project</title>
  </head>


  <body>
    <!--navbar start-->
    <div class="fixed-top">
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
          
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
            <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            <img src="{{ '/media/images/user.svg' }}">
          </a>
          
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
          {% if user.is_authenticated %}
            <li><a class="nav-link dropdown-item" href="">{{ user.username|title }}</a></li>
            <hr>
            <li class="selected">
            <a class="nav-link dropdown-item" href="{% url 'store:orders' %}" >Order History</a>
            </li>
            <li class="selected">
            <a class="nav-link dropdown-item" href="{% url 'store:roomorders' %}" >Booking History</a>
            </li>
            <li class="selected">
            <a class="nav-link dropdown-item" href="{% url 'store:logout' %}" >Logout</a>
            </li>
            {% else %}
            <li class="selected">
            <a class="nav-link dropdown-item" href="{% url 'store:signup' %}" >Signup</a>
            </li>
            <hr>
            <li class="selected">
            <a class="nav-link dropdown-item" href="{% url 'store:login' %}" >Login</a>
            </li>
            {% endif %}
            </ul>
            
        </li>
         
              <li class="nav-item">
                <a class="nav-link" href="{% url 'store:home' %}">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" aria-current="page" href="{% url 'store:menu' %}">Menu</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'store:rooms' %}">Book Rooms</a>
              </li>
              {% if user.is_authenticated %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'store:cart' %}">Cart</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'store:roomcart' %}">Bookings-Cart</a>
              </li>
              {% endif %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'store:about' %}">About</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'store:home' %}#ourteam">Our team</a>
              </li>

              {% if user.username == 'admin' %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'store:visualize' %}">Visualize</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'store:optimize' %}">Optimize</a>
              </li>
              {% endif %}
            </ul>
          </div>
        </div>
    </nav>
    

    </div>
    <!--navbar ends-->

    <br>
    <br>
    <br>
    <br>



    <!-- heading and search -->

    <div class="head">
        <h1>{{ category.name }}</h1>
        <form class="d-flex" style="float: right;" method="GET" action="{% url 'store:itemsearch' %}">
 {% csrf_token %}
    <input class="form-control me-2"  name="q"  value="{{request.GET.q}}"  type="text" placeholder="Search" aria-label="Search">
    <button class="btn btn-outline-dark" type="submit">Search</button>
</form> 
        <br>
    </div>
    <hr>


<!--for search-->

{% for result in results %}
        <div class="container-fluid mt-3 col-lg-9 mx-auto">
        <div class="row mx-auto">
            <br>
            <div class="col">
                <div class="card mx-auto mb-3" style="width: 18rem;">
                    <img src="{{ result.image.url }}" class="card-img-top" alt="...">
                    <div class="card-body">
                      <p class="card-text" id="item"><strong>🍽 {{result.name}}</strong></p>
                      <p class="card-text"><strong>&#8377;{{ result.price }} per serving</strong></p>
                      <a href="{{ result.get_absolute_url }}" class="btn btn-outline-danger">View</a>
                    </div>
                  </div>
            
        </div>
</div>
       {% endfor %}
</div>

<!--for search-->



    
    <div class="container-fluid mt-3 col-lg-9 mx-auto">
        <div class="row mx-auto">
        {% for i in nv %}
            <div class="col">
                <div class="card mx-auto mb-3" style="width: 18rem;">
                    <img src="{{ i.image.url }}" class="card-img-top" alt="...">
                    <div class="card-body">
                      <p class="card-text" id="item"><strong>🍽 {{i.name}}</strong></p>
                      <p class="card-text"><strong>&#8377;{{ i.price }} per serving</strong></p>
                      <a href="{{ i.get_absolute_url }}" class="btn btn-outline-danger">View</a>
                    </div>
                  </div>
            </div>  
        
       {% endfor %}
    </div>
    </div>
    </div>
    <br>
    <br>
    <br>
    <br>













    <!--page footer start-->
    <div class="bg-dark footer ">
        <div class="container">
           <div class="row text-center">
            <a href="home.html"><img src="{{ '/media/images/below-logo.jpeg' }}" ></a>
           </div>
    
           <hr style="color:gray">
    
           <div class="row text-center" style="color: ivory;">
             <div class="col">
               <ul>
                 
                  <h5><u>QUICK LINKS</u></h5>
                 
                 <li>
                  <a href="contact.html">contact us</a>
                </li>
                <li>
                  <a href="gallery.html">gallery</a>
                </li>
                <li>
                  <a href="home.html#ourteam">our team</a>
                </li>
                <li>
                  <a href="aboutus.html">about us</a>
                </li>
               </ul>
             </div>
    
             <div class="col">
              <h5><u>ADDRESS</u></h5> 
              <p>Cosmopolitan Restaurant,<br>Hyderabad.<br>pincode:500 020<br>email: abc@gmail.com</p>
             </div>
    
             <div class="col">
               <h5><u>VISIT US AT</u></h5>
               
               <a href="#facebook" class="fa fa-facebook"></a>
               <a href="https://youtu.be/mAFltQ2H8nA" class="fa fa-youtube"></a>
               <a href="#instagram" class="fa fa-instagram"></a>
             </div>
           </div>
        </div>
      </div>
        <!--page footer ends-->





</body>
</html>

store/templates/message.html
{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}